-- problem 1

    SELECT CDEPT, CNO, CNAME, CLABFEE, AVG_LABFEE 
FROM COURSE, (SELECT AVG(CLABFEE) AS "AVG_LABFEE" 
FROM COURSE)  
ORDER BY CNO; 

-- problem 2 

SELECT CDEPT, CNO, CNAME, CLABFEE,
        AVG(CLABFEE) OVER
        (PARTITION BY CDEPT
        ORDER BY CDEPT) AS "AVG_LABFEE"
FROM COURSE
ORDER BY CDEPT;

-- problem 3

SELECT FNAME, FDEPT, FSALARY,
    SUM(FSALARY) OVER 
    (PARTITION BY FDEPT
    ORDER BY FNAME) AS "DEPT_TOTAL",
    ROW_NUMBER() OVER
        (PARTITION BY FDEPT
        ORDER BY FNAME) AS "EMP #"
FROM FACULTY
ORDER BY FDEPT, FNAME;
/* work in progress */

-- problem 4

SELECT CDEPT, CNAME, CLABFEE, 
MAX(CLABFEE) OVER (PARTITION BY CDEPT 
    ORDER BY CDEPT) AS "DEPT_MAX_FEE"
FROM COURSE
ORDER BY CDEPT;

-- incomplete, must find difference between numbers 

-- problem 5 

SELECT * FROM (
SELECT CDEPT, CNAME, CLABFEE,
        RANK() OVER (PARTITION BY CDEPT
                    ORDER BY CLABFEE DESC) AS "RANK"
FROM COURSE)
WHERE RANK <= 2
