CREATE TABLE KEY_TABLE(
USER_KEY VARCHAR2(25) PRIMARY KEY,
MOVIE_KEY VARCHAR2(25) NOT NULL
);

CREATE TABLE USER_TABLE (USERNAME VARCHAR2 (10) PRIMARY KEY,
PASSWD VARCHAR2 (16) NOT NULL,
EMAIL VARCHAR2 (30) NOT NULL,
FNAME VARCHAR2 (25) NOT NULL,
LNAME VARCHAR2 (25) NOT NULL, 
SIGNUP_DATE DATE DEFAULT SYSDATE,
USER_KEY VARCHAR2(25) NOT NULL,
CONSTRAINT FK_USER_TABLE FOREIGN KEY (USER_KEY) REFERENCES KEY_TABLE(USER_KEY)
); 

CREATE TABLE MOVIE_TABLE (
TITLE VARCHAR2 (25) PRIMARY KEY,
MOVIE_KEY VARCHAR2(25) NOT NULL,
GENRE VARCHAR2 (20) NOT NULL, 
LENGHT VARCHAR2 (300) NOT NULL,
CONSTRAINT FK_MOVIE_TABLE FOREIGN KEY (MOVIE_KEY) REFERENCES KEY_TABLE (MOVIE_KEY)
);
