CREATE TABLE USER_TABLE (USERNAME VARCHAR2 (10), PRIMARY KEY,
PASSWORD VARCHAR2 (16) NOT NULL,
EMAIL VARCHAR2 (30) NOT NULL,
FNAME VARCHAR2 (25) NOT NULL,
LNAME VARCHAR2 (25) NOT NULL, 
SIGNUP_DATE DATE,
); 

CREATE TABLE MOVIE_TABLE (
TITLE VARCHAR2 (25), PRIMARY KEY,
/*MOVIE_KEY VARCHAR2(25), FOREIGN KEY, */
GENRE VARCHAR2 (20) NOT NULL, 
LENGHT NUMBER (300) NOT NULL,
);

CREATE TABLE KEY_TABLE(
USER_KEY VARCHAR2(25), PRIMARY KEY,
MOVIE_TABLE VARCHAR2(25), PRIMARY KEY
);
