CREATE TABLE KEY_TABLE(
USER_KEY VARCHAR2(25) NOT NULL,
MOVIE_KEY VARCHAR2(25) NOT NULL,
PRIMARY KEY (USER_KEY, MOVIE_KEY)
);

CREATE TABLE USER_TABLE (USERNAME VARCHAR2 (10),
PASSWD VARCHAR2 (16) NOT NULL,
EMAIL VARCHAR2 (30) NOT NULL,
FNAME VARCHAR2 (25) NOT NULL,
LNAME VARCHAR2 (25) NOT NULL, 
SIGNUP_DATE DATE DEFAULT SYSDATE,
USER_KEY VARCHAR2(25) NOT NULL,
CONSTRAINT PK_USER_TABLE PRIMARY KEY (USERNAME));

CREATE TABLE MOVIE_TABLE (
TITLE VARCHAR2 (25) PRIMARY KEY,
MOVIE_KEY VARCHAR2(25) NOT NULL,
GENRE VARCHAR2 (20) NOT NULL, 
LENGHT VARCHAR2 (300) NOT NULL);

DESCRIBE KEY_TABLE;
DESCRIBE USER_TABLE;
DESCRIBE MOVIE_TABLE;
